### ISSUE TITLE
Error LNK2019: unresolved external symbol 

### ISSUE THREAD

**Issue by omern1** [PJayB/HTTP#2]
`HTTPRequest.obj : error LNK2019: unresolved external symbol "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl HTTP::Base64Decode(void const *,unsigned long)" (?Base64Decode@HTTP@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PBXK@Z) referenced in function "bool __cdecl HTTP::DecodeAuth(char const *,struct HTTP::REQUEST_DATA *)" (?DecodeAuth@HTTP@@YA_NPBDPAUREQUEST_DATA@1@@Z)`
The Error is somewhere here:

``` C++
bool DecodeAuth(
    const char* authString,
    REQUEST_DATA* out)
{
    const char* cursor = authString;

    // Ensure it's "Basic"
    if (!Parse(cursor, "Basic"))
    {
        return false;
    }

    EatSpaces(cursor);

    // Decode the message
    String credentials = Base64Decode(/*this is the place where the error is encountered*/
        cursor,
        (SIZE_T) strlen(cursor));

    // Split it 
    String::size_type colonPos = credentials.find(':');
    out->AuthUser = credentials.substr(0, colonPos);
    out->AuthPassword = credentials.substr(colonPos + 1);
    out->AuthMode = AUTH_BASIC;

    return true;
}
```

**Comment by PJayB** [comment]
Make sure to compile and link HTTPBase64.cpp.
